name: 改进建议
description: 描述演示场景和希望改善的操作
title: "[建议] "
body:
  - type: textarea
    id: scenario
    attributes:
      label: 使用场景与遇到的问题
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 希望的行为
    validations:
      required: true
